(in-package #:orfeus/gui)

(defun display-number (value)
  (if value (format nil "~G" value) ""))

(defun parse-number (text &optional allow-empty)
  (if (and allow-empty (string= text ""))
      nil
      (let ((*read-eval* nil))
        (multiple-value-bind (value end) (read-from-string text nil nil)
          (unless (and (realp value) (= end (length text)))
            (error "Expected a number, got ~S." text))
          value))))

(defun project-table-records (project)
  (loop for job in (project-photos project)
        collect (list :file (file-namestring (photo-job-input-path job))
                      :settings (if (photo-job-overrides job)
                                    (format nil "~D override~:P" (/ (length (photo-job-overrides job)) 2))
                                    "Defaults")
                      :state "Idle"
                      :output (or (and (photo-job-output-path job)
                                       (file-namestring (photo-job-output-path job)))
                                  "Automatic"))))

(defun make-gui-preview-directory ()
  "Create and return a private temporary directory for one GUI run."
  (uiop:ensure-directory-pathname
   (sb-posix:mkdtemp
    (namestring (merge-pathnames "orfeus-gui-XXXXXX"
                                 (uiop:temporary-directory))))))

(defun delete-gui-preview-directory (directory)
  "Delete the private preview DIRECTORY and all files created in it."
  (when directory
    (uiop:delete-directory-tree directory :validate t :if-does-not-exist :ignore)))

(defun preview-pathname (preview-directory index job)
  (merge-pathnames
   (make-pathname :name (format nil "preview-~D-~A"
                                index
                                (pathname-name (photo-job-input-path job)))
                  :type "jpg")
   preview-directory))

(defun run-gui (project-or-path &key project-path)
  "Open the FLTK frontend for PROJECT-OR-PATH, a PROJECT or project pathname."
  (let* ((project (etypecase project-or-path
                    (project project-or-path)
                    ((or pathname string) (project-read project-or-path))))
         (model (make-gui-model :project project
                                :project-path (or project-path
                                                  (unless (typep project-or-path 'project)
                                                    (pathname project-or-path)))))
         (queue (make-gui-queue))
         (preview-directory (make-gui-preview-directory))
         window table canvas status progress preview-file controls before-p
         timeout-id (preview-generation 0))
    (labels ((status (text) (setf (cl-fltk:value status) text))
             (selected-job () (gui-model-selected-job model))
             (clear-published-preview ()
               (when preview-file
                 (forget-preview-file preview-file)
                 (setf preview-file nil))
               (when canvas
                 (cl-fltk:redraw canvas)))
             (update-table ()
               (cl-fltk:table-set-records table
                 '((:file "File" 220) (:settings "Settings" 100)
                   (:state "Preview" 90) (:output "Output" 170))
                 (project-table-records project)))
             (sync-controls ()
               (dolist (entry controls)
                 (destructuring-bind (key widget kind) entry
                   (setf (cl-fltk:value widget)
                         (ecase kind
                           (:number (display-number (gui-model-setting model key)))
                           (:text (or (gui-model-setting model key) ""))
                           (:boolean (if (gui-model-setting model key) "1" "0")))))))
             (select-row ()
               (let ((row (cl-fltk:table-selected-row table)))
                 (when (and (>= row 0) (< row (length (project-photos project))))
                   (setf (gui-model-selected-index model) row)
                   (clear-published-preview)
                   (sync-controls)
                   (status (format nil "Selected ~A" (file-namestring (photo-job-input-path (selected-job))))))))
             (move-selection (delta)
               (let* ((count (length (project-photos project)))
                      (index (and (plusp count)
                                  (max 0 (min (1- count) (+ (gui-model-selected-index model) delta))))))
                 (when index
                   (cl-fltk:table-select-row table index)
                   (setf (gui-model-selected-index model) index)
                   (clear-published-preview)
                   (sync-controls))))
             (publish-preview (path)
               (when (and preview-file (not (equal preview-file path)))
                 (forget-preview-file preview-file))
               (forget-preview-file path)
               (setf preview-file path)
               (cl-fltk:redraw canvas))
             (render-one (job preview-p)
               (let* ((index (position job (project-photos project) :test #'eq))
                      (input (photo-job-input-path job))
                      (output (if preview-p
                                  (preview-pathname preview-directory index job)
                                  (gui-photo-output-path model job)))
                      (settings (if (and preview-p before-p)
                                    (make-processing-settings)
                                    (processing-settings-with-overrides
                                     (project-defaults project)
                                     (photo-job-overrides job))))
                      (generation (when preview-p (incf preview-generation))))
                 (enqueue-gui-task
                  queue (if preview-p :preview :export)
                  (lambda ()
                    (queue-event queue (list :status (format nil "Rendering ~A" (file-namestring input))))
                    (if preview-p
                        (render-preview input output settings :if-exists :supersede)
                        (render-photo input output settings :if-exists :supersede))
                    (queue-event queue (if preview-p
                                           (list :preview generation index job output)
                                           (list :done output))))
                  :replace-kind (and preview-p :preview))))
             (render-selected (&optional (preview-p t))
               (when (selected-job) (render-one (selected-job) preview-p)))
             (render-all ()
               (dolist (job (project-photos project))
                 (render-one job nil)))
             (poll ()
               (dolist (event (drain-events queue))
                 (ecase (first event)
                   (:status (status (second event)))
                   (:preview
                    (when (gui-preview-event-current-p model event preview-generation)
                      (publish-preview (fifth event))
                      (status "Preview ready")))
                   (:done (status (format nil "Rendered ~A" (file-namestring (second event)))))
                   (:error (status (format nil "Error: ~A" (second event))))))
               (setf (cl-fltk:value progress)
                     (if (gui-queue-busy-p queue) "50" "0"))))
      (setf window (cl-fltk:make-window :width 1440 :height 900 :label "Orfeus" :app-id "org.orfeus.Orfeus"))
      (cl-fltk:apply-classic-theme)
      (cl-fltk:set-size-range window :min-width 1120 :min-height 720)
      (let ((menu (cl-fltk:make-menu-bar :parent window :x 0 :y 0 :width 1440 :height 24)))
        (cl-fltk:add-menu-item menu "File/Save Project" (lambda (&rest ignored) (declare (ignore ignored))
                                                          (if (gui-model-project-path model)
                                                              (progn (project-write project (gui-model-project-path model)) (status "Project saved"))
                                                              (status "No project pathname"))))
        (cl-fltk:add-menu-item menu "File/Quit" (lambda (&rest ignored) (declare (ignore ignored)) (cl-fltk:quit)))
        (cl-fltk:add-menu-item menu "Edit/Reset Selected" (lambda (&rest ignored) (declare (ignore ignored)) (gui-model-reset-selected model) (sync-controls) (update-table)))
        (cl-fltk:add-menu-item menu "Edit/Reset Defaults" (lambda (&rest ignored) (declare (ignore ignored))
                                                            (setf (project-defaults project) (make-processing-settings))
                                                            (sync-controls) (update-table) (render-selected t)))
        (cl-fltk:add-menu-item menu "View/Before-After" (lambda (&rest ignored) (declare (ignore ignored)) (setf before-p (not before-p)) (render-selected t)))
        (cl-fltk:add-menu-item menu "Process/Render Preview" (lambda (&rest ignored) (declare (ignore ignored)) (render-selected t)))
        (cl-fltk:add-menu-item menu "Process/Render Selected" (lambda (&rest ignored) (declare (ignore ignored)) (render-selected nil)))
        (cl-fltk:add-menu-item menu "Process/Render All" (lambda (&rest ignored) (declare (ignore ignored)) (render-all))))
      (let ((toolbar (cl-fltk:make-group :parent window :x 0 :y 24 :width 1440 :height 34)))
        (flet ((button (x label icon action)
                 (let ((widget (cl-fltk:make-button :parent toolbar :x x :y 4 :width 105 :height 26 :label label :callback (lambda (&rest ignored) (declare (ignore ignored)) (funcall action)))))
                   (cl-fltk:set-stock-icon widget icon) widget)))
          (button 4 "Save" :save (lambda () (when (gui-model-project-path model) (project-write project (gui-model-project-path model)))))
          (button 114 "Before/After" :reload (lambda () (setf before-p (not before-p)) (render-selected t)))
          (button 224 "Preview" :reload (lambda () (render-selected t)))
          (button 334 "Selected" :export (lambda () (render-selected nil)))
          (button 444 "Render all" :export #'render-all)))
      (setf table (cl-fltk:make-record-table :parent window :x 0 :y 58 :width 300 :height 790
                                             :columns '((:file "File" 220) (:settings "Settings" 100) (:state "Preview" 90) (:output "Output" 170))
                                             :records (project-table-records project)
                                             :callback (lambda (&rest ignored) (declare (ignore ignored)) (select-row))))
      (setf canvas (cl-fltk:make-canvas :parent window :x 300 :y 58 :width 820 :height 790
                                        :callback (lambda (widget event value)
                                                    (declare (ignore event value))
                                                    (cl-fltk:draw-color-rgb :red 32 :green 34 :blue 36)
                                                    (cl-fltk:draw-filled-rect (cl-fltk:widget-x widget) (cl-fltk:widget-y widget)
                                                                              (cl-fltk:widget-width widget) (cl-fltk:widget-height widget))
                                                    (when preview-file (draw-preview-file widget preview-file)))))
      (let ((panel (cl-fltk:make-panel :parent window :x 1120 :y 58 :width 320 :height 790 :label "Inspector"))
            (y 34))
        (labels ((number-control (key label &optional (allow-empty nil))
                   (let ((widget (cl-fltk:make-value-input :parent panel :x 130 :y y :width 170 :height 24 :label label
                                                           :callback (lambda (widget event value)
                                                                       (declare (ignore event value))
                                                                       (handler-case (progn (gui-model-set-setting model key (parse-number (cl-fltk:value widget) allow-empty))
                                                                                            (update-table) (render-selected t))
                                                                         (error (condition) (status (princ-to-string condition))))))))
                     (push (list key widget :number) controls) (incf y 30)))
                 (boolean-control (key label)
                   (let ((widget (cl-fltk:make-check-button :parent panel :x 130 :y y :width 170 :height 24 :label label
                                                            :callback (lambda (widget event value)
                                                                        (declare (ignore event value))
                                                                        (gui-model-set-setting model key (string/= "0" (cl-fltk:value widget)))
                                                                        (render-selected t)))))
                     (push (list key widget :boolean) controls) (incf y 30))))
          (let ((target (cl-fltk:make-choice :parent panel :x 130 :y y :width 170 :height 24 :label "Edit target" :items '("Photo" "Defaults")
                                             :callback (lambda (widget event value) (declare (ignore event value))
                                                         (setf (gui-model-edit-target model) (if (string-equal (cl-fltk:value widget) "Defaults") :defaults :photo))))))
            (setf (cl-fltk:value target) "Photo") (incf y 34))
          (number-control :exposure "Exposure")
          (number-control :white-balance-temperature "WB temperature" t)
          (number-control :white-balance-tint "WB tint")
          (number-control :noise-reduction "Noise")
          (boolean-control :lens-correction-p "Lens correction")
          (boolean-control :chromatic-aberration-correction-p "Remove TCA")
          (let ((widget (cl-fltk:make-input :parent panel :x 130 :y y :width 170 :height 24 :label "LUT path"
                                            :callback (lambda (widget event value) (declare (ignore event value))
                                                        (gui-model-set-setting model :lut-path (unless (string= "" (cl-fltk:value widget)) (cl-fltk:value widget)))
                                                        (render-selected t)))))
            (push (list :lut-path widget :text) controls) (incf y 30))
          (number-control :lut-strength "LUT strength")
          (number-control :grain-amount "Grain amount")
          (number-control :grain-size "Grain size")
          (cl-fltk:make-button :parent panel :x 20 :y y :width 135 :height 28 :label "Reset photo"
                               :callback (lambda (&rest ignored) (declare (ignore ignored)) (gui-model-reset-selected model) (sync-controls) (update-table) (render-selected t)))
          (cl-fltk:make-button :parent panel :x 165 :y y :width 135 :height 28 :label "Render selected"
                               :callback (lambda (&rest ignored) (declare (ignore ignored)) (render-selected nil)))))
      (cl-fltk:on window
                  (lambda (widget event value)
                    (declare (ignore widget event))
                    (case (gui-key-action value)
                       (:before-after (setf before-p (not before-p)) (render-selected t))
                       (:preview (render-selected t))
                       (:render (render-selected nil))
                       (:previous (move-selection -1))
                       (:next (move-selection 1))))
                  :event cl-fltk:+event-key+)
      (setf progress (cl-fltk:make-progress :parent window :x 0 :y 848 :width 240 :height 26 :value "0")
            status (cl-fltk:make-status-bar :parent window :x 240 :y 848 :width 1200 :height 26 :value "Ready"))
      (sync-controls)
      (setf timeout-id (cl-fltk:add-timeout 0.1d0 #'poll :repeat t))
        (unwind-protect
             (progn
               (cl-fltk:show window)
               (cl-fltk:run))
          (when timeout-id
            (ignore-errors (cl-fltk:remove-timeout timeout-id)))
          (stop-gui-queue queue)
          (clear-preview-cache)
          (ignore-errors (delete-gui-preview-directory preview-directory))
          (when window
            (ignore-errors (cl-fltk:destroy window)))))))
