(defpackage #:orfeus/tests
  (:use #:cl)
  (:import-from #:orfeus
                #:cli-run
                #:orfeus-version
                #:orfeus-build-commit
                #:orfeus-build-description
                #:export-settings-jpeg-quality
                #:export-settings-max-height
                #:export-settings-max-width
                #:export-settings-preserve-metadata-p
                #:export-settings-timestamp-filenames-p
                #:invalid-project-data
                #:lens-profile-aliases-read
                #:lens-profile-alias-save
                #:processing-settings-chromatic-aberration-source
                #:resolve-lens-profile-alias
                #:make-export-settings
                #:make-photo-job
                #:make-processing-preset
                #:make-processing-settings
                #:make-project
                #:orfeus-version
                #:output-file-exists
                #:photo-extract-embedded-preview
                #:photo-job-input-path
                #:photo-job-overrides
                #:photo-job-render-output
                #:processing-preset-name
                #:processing-preset-settings
                #:processing-preset-graph
                #:still-store-write
                #:still-store-write-thumbnail
                #:still-store-identity
                #:still-store-list
                #:still-store-rename
                #:still-store-delete
                #:*maximum-curve-points*
                #:file-content-key
                #:forget-content-key
                #:default-processing-graph
                #:grade-stage-keys
                #:grade-stages
                #:graph->sexp
                #:graph-consumers
                #:graph-delete-node
                #:graph-effective-nodes
                #:graph-find-node
                #:graph-insert-node
                #:graph-insertion-point
                #:graph-can-insert-p
                #:graph-insertable-kinds
                #:graph-node-kinds
                #:graph-display-domain-p
                #:graph-kind-accepts-display-p
                #:*graph-source-id*
                #:graph-node-bypassed-p
                #:graph-node-inputs
                #:graph-node-kind
                #:graph-node-opacity
                #:graph-node-params
                #:graph-node-id
                #:graph-swap-with-upstream
                #:graph-move-node-after
                #:graph-set-blend-input
                #:graph-set-node-kind
                #:graph-set-primary-input
                #:graph-set-output
                #:*graph-source-id*
                #:graph-validate
                #:make-graph-node
                #:make-processing-graph
                #:photo-job-graph
                #:processing-graph-nodes
                #:processing-graph-output
                #:sexp->graph
                #:settings->graph
                #:next-still-preset-name
                #:photo-job-apply-grade
                #:photo-job-disabled-stages
                #:photo-render-settings
                #:processing-preset-disabled-stages
                #:processing-preset-source-photo
                #:processing-settings-exposure
                #:processing-settings-grain-amount
                #:processing-settings-lens-correction-strength
                #:processing-settings-lut-path
                #:processing-settings-lut-strength
                #:processing-settings-neural-noise-reduction
                #:processing-settings-noise-reduction
                #:processing-settings-tone-shadows
                #:processing-settings-with-overrides
                #:settings-grade-plist
                #:project->sexp
                #:project-defaults
                #:project-export-settings
                #:project-output-directory
                #:project-photos
                #:project-presets
                #:project-read
                #:project-write
                #:raw-render-error
                #:render-photo
                #:render-preview
                #:sexp->processing-settings
                #:sexp->project)
  (:export #:run-tests))

(in-package #:orfeus/tests)
