(defpackage #:orfeus
  (:use #:cl)
  (:import-from #:cffi
                #:defcfun
                #:defcstruct
                #:foreign-slot-value
                #:foreign-string-to-lisp
                #:foreign-type-size
                #:load-foreign-library
                #:null-pointer
                #:with-foreign-object
                #:with-foreign-pointer
                #:with-foreign-string)
  (:import-from #:sb-posix
                #:eexist
                #:link
                #:stat
                #:stat-dev
                #:stat-ino
                #:syscall-errno
                #:syscall-error)
  (:export
   #:cli-run
   #:dng-extract-original
   #:dng-original-error
   #:dng-original-filename
   #:export-settings
   #:export-settings-jpeg-quality
   #:export-settings-max-height
   #:export-settings-max-width
   #:export-settings-preserve-metadata-p
   #:invalid-project-data
   #:lens-profile-aliases-pathname
   #:lens-profile-aliases-read
   #:resolve-lens-profile-alias
   #:main
   #:make-export-settings
   #:make-photo-job
   #:make-processing-preset
   #:make-processing-settings
   #:make-project
   #:native-bridge-available-p
   #:native-bridge-version
   #:native-library-incompatible
   #:native-library-unavailable
   #:orfeus-error
   #:orfeus-version
   #:output-file-exists
   #:photo-capture-description
   #:photo-extract-embedded-preview
   #:photo-lens-description
   #:photo-job
   #:photo-job-input-path
   #:photo-job-output-path
   #:photo-job-overrides
   #:photo-job-disabled-stages
   #:photo-job-apply-grade
   #:photo-render-settings
   #:grade-stages
   #:grade-stage-keys
   #:settings-apply-stage-bypass
   #:settings-grade-plist
   #:next-still-preset-name
   #:graph-node
   #:make-graph-node
   #:graph-node-id
   #:graph-node-kind
   #:graph-node-params
   #:graph-node-opacity
   #:graph-node-inputs
   #:graph-node-bypassed-p
   #:graph-node-blend-p
   #:graph-node-filter-p
   #:processing-graph
   #:make-processing-graph
   #:copy-processing-graph
   #:processing-graph-nodes
   #:processing-graph-output
   #:graph-validate
   #:graph-copy
   #:graph->sexp
   #:sexp->graph
   #:settings->graph
   #:graph-effective-nodes
   #:graph-find-node
   #:graph-consumers
   #:graph-insert-node
   #:graph-delete-node
   #:graph-swap-with-upstream
   #:default-processing-graph
   #:photo-job-graph
   #:processing-preset-graph
   #:processing-preset
   #:processing-preset-disabled-stages
   #:processing-preset-name
   #:processing-preset-settings
   #:processing-preset-source-photo
   #:processing-settings
   #:processing-settings-chromatic-aberration-correction-p
   #:processing-settings-exposure
   #:processing-settings-grain-amount
   #:processing-settings-grain-size
   #:processing-settings-lens-correction-p
   #:processing-settings-lens-correction-strength
   #:processing-settings-lut-path
   #:processing-settings-lut-strength
   #:processing-settings-noise-reduction
   #:processing-settings-neural-noise-reduction
   #:processing-settings-tone-blacks
   #:processing-settings-tone-shadows
   #:processing-settings-tone-dark-mids
   #:processing-settings-tone-midtones
   #:processing-settings-tone-light-mids
   #:processing-settings-tone-highlights
   #:processing-settings-tone-whites
   #:processing-settings-white-balance-temperature
   #:processing-settings-white-balance-tint
   #:processing-settings-with-overrides
   #:photo-job-render-output
   #:project
   #:project-defaults
   #:project-export-settings
   #:project-output-directory
   #:project-photos
   #:project-presets
   #:project-read
   #:project-render
   #:project-write
   #:project->sexp
   #:raw-render-error
   #:render-photo
   #:render-photo-job
   #:render-preview
   #:sexp->project))

(in-package #:orfeus)
