(defpackage #:orfeus
  (:use #:cl)
  (:import-from #:cffi
                #:defcfun
                #:defcstruct
                #:foreign-slot-value
                #:foreign-string-to-lisp
                #:foreign-type-size
                #:load-foreign-library
                #:null-pointer
                #:with-foreign-object
                #:with-foreign-pointer
                #:with-foreign-string)
  (:import-from #:sb-posix
                #:eexist
                #:link
                #:stat
                #:stat-dev
                #:stat-ino
                #:syscall-errno
                #:syscall-error)
  (:export
   #:cli-run
   #:dng-extract-original
   #:dng-original-error
   #:dng-original-filename
   #:invalid-project-data
   #:main
   #:make-photo-job
   #:make-processing-settings
   #:make-project
   #:native-bridge-available-p
   #:native-bridge-version
   #:native-library-incompatible
   #:native-library-unavailable
   #:orfeus-error
   #:orfeus-version
   #:output-file-exists
   #:photo-extract-embedded-preview
   #:photo-job
   #:photo-job-input-path
   #:photo-job-output-path
   #:photo-job-overrides
   #:processing-settings
   #:processing-settings-chromatic-aberration-correction-p
   #:processing-settings-exposure
   #:processing-settings-grain-amount
   #:processing-settings-grain-size
   #:processing-settings-lens-correction-p
   #:processing-settings-lut-path
   #:processing-settings-lut-strength
   #:processing-settings-noise-reduction
   #:processing-settings-white-balance-temperature
   #:processing-settings-white-balance-tint
   #:processing-settings-with-overrides
   #:photo-job-render-output
   #:project
   #:project-defaults
   #:project-output-directory
   #:project-photos
   #:project-read
   #:project-render
   #:project-write
   #:project->sexp
   #:raw-render-error
   #:render-photo
   #:render-preview
   #:sexp->project))

(in-package #:orfeus)
